// File generated by generate_ast on 22-Jul-2023 16:47:46 +10:00
#pragma warning disable 1591

namespace cslox;

public abstract record Expr
{
    public interface IVisitor<R>
    {
        R VisitBinaryExpr(Binary expr);
        R VisitGroupingExpr(Grouping expr);
        R VisitLiteralExpr(Literal expr);
        R VisitUnaryExpr(Unary expr);
    }

    public abstract R Accept<R>(IVisitor<R> visitor);

    public record Binary(Expr Left, Token Operator, Expr Right) : Expr
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitBinaryExpr(this);
        }
    }

    public record Grouping(Expr Expression) : Expr
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitGroupingExpr(this);
        }
    }

    public record Literal(object Value) : Expr
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitLiteralExpr(this);
        }
    }

    public record Unary(Token Operator, Expr Right) : Expr
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitUnaryExpr(this);
        }
    }

}

#pragma warning restore 1591
