// File generated by generate_ast on 29-Sep-2023 17:28:21 +10:00
#pragma warning disable 1591

namespace cslox;

public abstract record Stmt
{
    public interface IVisitor<R>
    {
        R VisitExpressionStatementStmt(ExpressionStatement stmt);
        R VisitPrintStmt(Print stmt);
        R VisitVarStmt(Var stmt);
    }

    public abstract R Accept<R>(IVisitor<R> visitor);

    public record ExpressionStatement(Expr Expression) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitExpressionStatementStmt(this);
        }
    }

    public record Print(Expr Expression) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitPrintStmt(this);
        }
    }

    public record Var(Token Name, Expr? Initializer) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitVarStmt(this);
        }
    }

}

#pragma warning restore 1591
