// File generated by generate_ast on 29-Jun-2025 23:55:02 +10:00
#pragma warning disable 1591

namespace cslox;

public abstract record Stmt
{
    public interface IVisitor<R>
    {
        R VisitBlockStmt(Block stmt);
        R VisitClassStmt(Class stmt);
        R VisitExpressionStatementStmt(ExpressionStatement stmt);
        R VisitFunctionStmt(Function stmt);
        R VisitIfStmt(If stmt);
        R VisitPrintStmt(Print stmt);
        R VisitReturnStmt(Return stmt);
        R VisitWhileStmt(While stmt);
        R VisitVarStmt(Var stmt);
    }

    public abstract R Accept<R>(IVisitor<R> visitor);

    public record Block(List<Stmt?> Statements) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitBlockStmt(this);
        }
    }

    public record Class(Token Name, Expr.Variable? Superclass, List<Stmt.Function> Methods) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitClassStmt(this);
        }
    }

    public record ExpressionStatement(Expr Expression) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitExpressionStatementStmt(this);
        }
    }

    public record Function(Token Name, List<Token> Params, List<Stmt?> Body) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitFunctionStmt(this);
        }
    }

    public record If(Expr Condition, Stmt ThenBranch, Stmt? ElseBranch) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitIfStmt(this);
        }
    }

    public record Print(Expr Expression) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitPrintStmt(this);
        }
    }

    public record Return(Token Keyword, Expr? Value) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitReturnStmt(this);
        }
    }

    public record While(Expr Condition, Stmt Body) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitWhileStmt(this);
        }
    }

    public record Var(Token Name, Expr? Initializer) : Stmt
    {
        public override R Accept<R>(IVisitor<R> visitor)
        {
            return visitor.VisitVarStmt(this);
        }
    }

}

#pragma warning restore 1591
